/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBackground: typeof import('./src/components/AppBackground.vue')['default']
    Button: typeof import('primevue/button')['default']
    HideScrollbar: typeof import('./src/components/HideScrollbar.vue')['default']
    MediaCard: typeof import('./src/components/MediaCard.vue')['default']
    MetadataLoader: typeof import('./src/components/MetadataLoader.vue')['default']
    PageWrapper: typeof import('./src/components/PageWrapper.vue')['default']
    PeopleList: typeof import('./src/components/PeopleList.vue')['default']
    ProgressBar: typeof import('./src/components/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StarRating: typeof import('./src/components/StarRating.vue')['default']
    SwapView: typeof import('./src/components/SwapView.vue')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    VideoPlayer: typeof import('./src/components/VideoPlayer.vue')['default']
  }
}
